#!/usr/bin/env python3
import argparse
import os
parser = argparse.ArgumentParser()

parser.add_argument('a')
parser.add_argument('b')
parser.add_argument('c')

args = parser.parse_args()

pa = os.path.expanduser(args.a)
pb = os.path.expanduser(args.b)
pc = os.path.expanduser(args.c)

import healpy as hp

def load(path):
    try:
        a = hp.read_map(path, (0,1,2))
    except:
        a = hp.read_map(path)
    return a

a = load(pa)
b = load(pb)

c = a + b
hp.write_map(pc, c)
